description: <small>Example documentation of <a href="https://github.com/competitive-verifier/competitive-verifier">competitive-verifier/competitive-verifier</a></small>
highlightjs-style: routeros
filename-index: true
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
consolidate:
- examples/rust