[languages.awk]
compile = "ls {tempdir}"
execute = { "command" = "awk -f {path}", env = { "AWKPATH" = "{basedir}" } }
bundle = "false"
list_dependencies = "sed 's/^@include \"\\(.*\\)\"$/\\1/ ; t ; d' {path}"

[languages.txt]
compile = "true"
execute = "true"
bundle = "normalizer {path} -m"
list_dependencies = ""
