[languages.awk]
compile = "bash -c 'echo hello > {tempdir}/hello'"
execute = "env AWKPATH={basedir} awk -f {path}"
bundle = "false"
list_dependencies = "sed 's/^@include \"\\(.*\\)\"$/\\1/ ; t ; d' {path}"

[languages.txt]
compile = "true"
execute = "true"
bundle = "false"
list_dependencies = ""

[languages.hello]
execute = { command = "tail -n 1 {path}", cwd = "{basedir}" }
compile = "true"
bundle = "false"
list_dependencies = 'find {basedir} -type f -name "*.hello"'
