name: example

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  YUKICODER_TOKEN: ${{secrets.YUKICODER_TOKEN}}

jobs:
  test-example:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Cache
        uses: actions/cache@v3
        with:
          path: .competitive-verifier/cache
          key: verifier-example-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            verifier-example-${{ runner.os }}

      - name: Run download
        run: poetry run competitive-verifier download examples/awk/verify_files.json
