name: example awk

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  YUKICODER_TOKEN: ${{secrets.YUKICODER_TOKEN}}
  COMPETITIVE_VERIFY_FILES_PATH: .competitive-verifier/tmp/awk-verify-files.json

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      artifact-path: .competitive-verifier/tmp/
    outputs:
      artifact-path: ${{ env.artifact-path }}
      verify-json: ${{ steps.create-json.outputs.verify-json  }}
      hash: ${{ steps.create-hash.outputs.hash  }}
    steps:
      - uses: actions/checkout@v3

      - name: Create verify-files.json
        id: create-json
        run: |
          mkdir -p .competitive-verifier/tmp
          cp examples/awk/verify_files.json $COMPETITIVE_VERIFY_FILES_PATH
      - name: Create hash
        id: create-hash
        run: |
          echo "hash=${{ hashFiles('**/*verify-files.json') }}" > $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v3
        with:
          name: setup-${{ runner.os }}
          path: ${{ env.artifact-path }}
          retention-days: 1

  download:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: setup-${{ runner.os }}
          path: ${{ needs.setup.outputs.artifact-path }}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: .competitive-verifier/cache
          key: verifier-${{ runner.os }}-${{ needs.setup.outputs.hash }}
          restore-keys: |
            verifier-${{ runner.os }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install competitive-verifier
        run: pip install git+https://github.com/competitive-verifier/competitive-verifier.git

      - name: Run download
        run: competitive-verifier download
        env:
          YUKICODER_TOKEN: ${{secrets.YUKICODER_TOKEN}}

  verify:
    runs-on: ubuntu-latest
    needs: [setup, download]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: setup-${{ runner.os }}
          path: ${{ needs.setup.outputs.artifact-path }}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: .competitive-verifier/cache
          key: verifier-${{ runner.os }}-${{ needs.setup.outputs.hash }}
          restore-keys: |
            verifier-${{ runner.os }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install competitive-verifier
        run: pip install git+https://github.com/competitive-verifier/competitive-verifier.git

      - name: Run verify
        run: competitive-verifier verify --no-download
