name: example oj python

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  COMPETITIVE_VERIFY_FILES_PATH: .competitive-verifier/tmp/py-verify-files.json

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      artifact-path: .competitive-verifier/tmp/
    outputs:
      verify-json: ${{ steps.create-json.outputs.verify-json  }}
      hash: ${{ steps.create-hash.outputs.hash  }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install competitive-verifier
        run: pip install git+https://github.com/competitive-verifier/competitive-verifier.git

      - name: Create verify-files.json
        id: create-json
        run: |
          delimiter=$(uuidgen)
          echo "verify-json<<$delimiter" >> $GITHUB_OUTPUT
          competitive-verifier oj-resolve >> $GITHUB_OUTPUT
          echo "$delimiter" >> $GITHUB_OUTPUT
      - name: Create hash
        id: create-hash
        run: |
          echo "hash=${{ hashFiles('**/*verify-files.json') }}" >> $GITHUB_OUTPUT

  download:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
      - name: verify-files.json
        run: |
          mkdir $(dirname $COMPETITIVE_VERIFY_FILES_PATH)
          delimiter=$(uuidgen)
          cat - <<$delimiter > $COMPETITIVE_VERIFY_FILES_PATH
          ${{ needs.setup.outputs.verify-json }}
          $delimiter
      - name: Cache
        uses: actions/cache@v3
        with:
          path: .competitive-verifier/cache
          key: verifier-${{ runner.os }}-${{ needs.setup.outputs.hash }}
          restore-keys: |
            verifier-${{ runner.os }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install competitive-verifier
        run: pip install git+https://github.com/competitive-verifier/competitive-verifier.git

      - name: Run download
        run: competitive-verifier download
        env:
          YUKICODER_TOKEN: ${{secrets.YUKICODER_TOKEN}}

  verify:
    runs-on: ubuntu-latest
    needs: [setup, download]
    strategy:
      matrix:
        index:
          [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
    outputs:
      verify-json: ${{ steps.verify.outputs.verify-result  }}
    steps:
      - uses: actions/checkout@v3
      - name: verify-files.json
        run: |
          mkdir $(dirname $COMPETITIVE_VERIFY_FILES_PATH)
          delimiter=$(uuidgen)
          cat - <<$delimiter > $COMPETITIVE_VERIFY_FILES_PATH
          ${{ needs.setup.outputs.verify-json }}
          $delimiter

      - name: Cache
        uses: actions/cache@v3
        with:
          path: .competitive-verifier/cache
          key: verifier-${{ runner.os }}-${{ needs.setup.outputs.hash }}
          restore-keys: |
            verifier-${{ runner.os }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install competitive-verifier
        run: pip install git+https://github.com/competitive-verifier/competitive-verifier.git

      - name: Run verify
        id: verify
        run: |
          RESULT_PATH=$(dirname $COMPETITIVE_VERIFY_FILES_PATH)/result${{ matrix.index }}.json
          competitive-verifier verify --split 20 --split-index ${{ matrix.index }}
