name: format

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "src/**.py"
      - "tests/**.py"
      - pyproject.toml

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run linter
        run: poetry run poe lint

      - name: Dump schema
        run: |
          poetry run poe -q schema-verify_files > schema/verify_files.schema.json
          poetry run poe -q schema-verify_result > schema/verify_result.schema.json
          poetry run poe -q schema-config_yml > .competitive-verifier/docs/_config.default.yml

      - name: Git diff
        run: git diff --exit-code