name: test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python }}"
          cache: "poetry"

      - name: Install dependencies (Java)
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
      - name: Install dependencies (Go)
        uses: actions/setup-go@v4
      - name: Set up Rust (1.42.0)
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.42.0"
          targets: x86_64-unknown-linux-gnu

      - name: Install dependencies
        run: poetry install --with test

      - name: GNU time
        if: runner.os == 'macOS'
        run: brew install gnu-time

      - name: Run test
        run: poetry run pytest -vv